# Declare phony targets

# Declare directories
CONFIG_DIR := /home/phantomwise/SynologyDrive/dotfiles-nix/nix
PERSONAL_DIR := /home/phantomwise/SynologyDrive/Personal
HOME_DIR := /home/phantomwise

# Include modular Makefile parts
include nix-cleanup.mk
include nix-update.mk
include stow.mk
